# Generated by Django 4.1 on 2022-09-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_customer_user_daytrips_image_tour_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='days',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
